services:
  dfe.complete:
    image: ${DOCKER_REGISTRY-}dfecomplete
    build:
      context: .
      dockerfile: src/Frontend/Dfe.Complete/Dockerfile
    ports:
       - 5003:8081
       - 5002:8080
    networks:
      - local-dev
  
  dfe.complete.api:
    image: ${DOCKER_REGISTRY-}dfecompleteapi
    build:
      context: .
      dockerfile: src/Api/Dfe.Complete.Api/Dockerfile
    ports:
       - 7089:8081
       - 5277:8080
    networks:
      - local-dev

networks:
  local-dev:
